model_name: "FacebookAI/xlm-roberta-base"
num_labels: 1  # Regression head


model_dir: "../models"
results_dir: "../results"
num_train_epochs: 3
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
weight_decay: 0.01
evaluation_strategy: "epoch"
logging_strategy: "epoch"
save_strategy: "epoch"
learning_rate: 2e-5

# Danish/English data selection for merging
num_danish_samples: 0      # Number of Danish samples to include
num_english_samples: 20       # Number of English samples to include
danish_score_min: 0             # Optional: minimum educational score (inclusive)
danish_score_max: 4             # Optional: maximum educational score (inclusive)
danish_random_seed: 42          # Optional: random seed for sampling
