model_name: "FacebookAI/xlm-roberta-large"
num_labels: 5

train_data_path: "../../train-00000-of-00001.parquet"
eval_data_path: "../../eval-00000-of-00001.parquet"

output_dir: "../results"
num_train_epochs: 3
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
weight_decay: 0.01
evaluation_strategy: "epoch"
save_strategy: "epoch"

# Danish data selection for merging
num_danish_samples: 500
danish_score_min: 4
danish_score_max: 5
danish_random_seed: 123